# Generated by Django 4.0.5 on 2022-06-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=200, unique=True)),
                ('origin', models.CharField(max_length=250)),
                ('occurrence', models.CharField(max_length=250)),
                ('body_type', models.CharField(max_length=200)),
                ('coat_type_and_length', models.CharField(max_length=200)),
                ('coat_pattern', models.CharField(max_length=200)),
                ('image', models.URLField(max_length=500)),
                ('intro', models.TextField()),
                ('description', models.TextField()),
                ('history', models.TextField()),
            ],
        ),
    ]
